// database/seeders/rrhh_preguntas_seeder.ts
import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { DateTime } from 'luxon'
import RrhhPregunta from '#models/rrhh_pregunta'

export default class RrhhPreguntasSeeder extends BaseSeeder {
  public async run() {
    await RrhhPregunta.updateOrCreateMany('id', [
      {
        id: 50,
        examen_id: 49,
        texto: '¿Qué harías si encuentras dinero tirado?',
        peso_pregunta: 1.0,
        a: 'Ignorarlo',
        peso_a: 0.1,
        b: 'Preguntar de quién es',
        peso_b: 0.3,
        c: 'Guardarlo para después devolverlo',
        peso_c: 0.5,
        d: 'No lo toco',
        peso_d: 0.1,
        e: 'Devolverlo',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 51,
        examen_id: 49,
        texto: 'Si ves a alguien en apuros, ¿qué haces?',
        peso_pregunta: 1.0,
        a: 'Ayudar de inmediato',
        peso_a: 1.0,
        b: 'No hago nada',
        peso_b: 0.2,
        c: 'Ignorar la situación',
        peso_c: 0.1,
        d: 'Esperar a que alguien más ayude',
        peso_d: 0.2,
        e: 'Preguntar si necesita ayuda',
        peso_e: 0.5,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 52,
        examen_id: 49,
        texto: '¿Cómo reaccionas si alguien te insulta?',
        peso_pregunta: 1.0,
        a: 'Lo ignoro',
        peso_a: 1.0,
        b: 'Me enojo',
        peso_b: 0.3,
        c: 'Respondo con insultos',
        peso_c: 0.1,
        d: 'Busco ayuda',
        peso_d: 0.4,
        e: 'Intento calmar la situación',
        peso_e: 0.8,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 53,
        examen_id: 49,
        texto: '¿Qué haces si ves a alguien con hambre?',
        peso_pregunta: 1.0,
        a: 'Me alejo',
        peso_a: 0.1,
        b: 'Le doy dinero',
        peso_b: 0.5,
        c: 'Le ofrezco comida',
        peso_c: 1.0,
        d: 'Busco a alguien para ayudarle',
        peso_d: 0.7,
        e: 'Espero a que lo resuelva solo',
        peso_e: 0.2,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 54,
        examen_id: 49,
        texto: 'Si un compañero se equivoca, ¿cómo reaccionas?',
        peso_pregunta: 1.0,
        a: 'Lo ignoro',
        peso_a: 0.2,
        b: 'Lo apoyo para corregirlo',
        peso_b: 1.0,
        c: 'Lo culpo frente a todos',
        peso_c: 0.1,
        d: 'Dejo que lo resuelva',
        peso_d: 0.4,
        e: 'Ofrezco ayuda solo si me lo pide',
        peso_e: 0.6,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 55,
        examen_id: 49,
        texto: '¿Qué haces si encuentras un objeto perdido?',
        peso_pregunta: 1.0,
        a: 'Me lo quedo',
        peso_a: 0.1,
        b: 'Lo guardo',
        peso_b: 0.2,
        c: 'Lo llevo a objetos perdidos',
        peso_c: 0.8,
        d: 'Lo dejo donde está',
        peso_d: 0.3,
        e: 'Busco al dueño',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 56,
        examen_id: 49,
        texto: '¿Cómo reaccionas si ves una injusticia?',
        peso_pregunta: 1.0,
        a: 'Intento detenerla',
        peso_a: 1.0,
        b: 'Espero a que otro actúe',
        peso_b: 0.3,
        c: 'Me quedo callado',
        peso_c: 0.2,
        d: 'Me uno a la injusticia',
        peso_d: 0.1,
        e: 'Busco ayuda',
        peso_e: 0.7,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 57,
        examen_id: 49,
        texto: '¿Qué harías si ves a alguien siendo acosado?',
        peso_pregunta: 1.0,
        a: 'Lo ignoro',
        peso_a: 0.1,
        b: 'Busco ayuda',
        peso_b: 0.8,
        c: 'Cambio de tema',
        peso_c: 0.2,
        d: 'Lo defiendo',
        peso_d: 1.0,
        e: 'Le digo que lo reporte',
        peso_e: 0.5,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 58,
        examen_id: 49,
        texto: 'Si tienes la oportunidad de ayudar, ¿cómo actúas?',
        peso_pregunta: 1.0,
        a: 'Espero a que lo pidan',
        peso_a: 0.3,
        b: 'Me niego',
        peso_b: 0.1,
        c: 'Ayudo sin dudar',
        peso_c: 1.0,
        d: 'Pienso si es mi responsabilidad',
        peso_d: 0.4,
        e: 'Sugiero otra solución',
        peso_e: 0.5,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 59,
        examen_id: 49,
        texto: '¿Qué harías si ves un accidente?',
        peso_pregunta: 1.0,
        a: 'Pregunto qué pasó',
        peso_a: 0.2,
        b: 'Me voy sin involucrarme',
        peso_b: 0.1,
        c: 'Ayudo a las personas afectadas',
        peso_c: 1.0,
        d: 'Llamo a emergencias',
        peso_d: 0.9,
        e: 'Grabo un video',
        peso_e: 0.1,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 60,
        examen_id: 50,
        texto: '¿Cómo reaccionas ante un problema inesperado?',
        peso_pregunta: 1.0,
        a: 'Me desanimo',
        peso_a: 0.2,
        b: 'Busco ayuda',
        peso_b: 0.6,
        c: 'Ignoro el problema',
        peso_c: 0.1,
        d: 'Busco una solución',
        peso_d: 1.0,
        e: 'Me quejo',
        peso_e: 0.1,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 61,
        examen_id: 50,
        texto: 'Si fallas en algo importante, ¿qué haces?',
        peso_pregunta: 1.0,
        a: 'Me desmotivo',
        peso_a: 0.3,
        b: 'Me doy por vencido',
        peso_b: 0.2,
        c: 'Intento otra vez',
        peso_c: 0.8,
        d: 'Culpo a los demás',
        peso_d: 0.1,
        e: 'Aprendo de mi error',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 62,
        examen_id: 50,
        texto: '¿Cómo enfrentas una crítica negativa?',
        peso_pregunta: 1.0,
        a: 'Me enfado',
        peso_a: 0.1,
        b: 'La ignoro',
        peso_b: 0.3,
        c: 'La tomo como aprendizaje',
        peso_c: 1.0,
        d: 'Respondo agresivamente',
        peso_d: 0.2,
        e: 'Intento mejorar',
        peso_e: 0.9,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 63,
        examen_id: 50,
        texto: '¿Qué haces si un proyecto no sale como esperabas?',
        peso_pregunta: 1.0,
        a: 'Me quejo con los demás',
        peso_a: 0.2,
        b: 'Busco apoyo',
        peso_b: 0.7,
        c: 'Renuncio al proyecto',
        peso_c: 0.1,
        d: 'Intento corregirlo',
        peso_d: 0.9,
        e: 'Analizo qué salió mal',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 64,
        examen_id: 50,
        texto: '¿Cómo reaccionas ante un desafío difícil?',
        peso_pregunta: 1.0,
        a: 'Lo veo como una oportunidad',
        peso_a: 1.0,
        b: 'Me estreso',
        peso_b: 0.1,
        c: 'Pido ayuda',
        peso_c: 0.8,
        d: 'Lo abandono',
        peso_d: 0.3,
        e: 'Lo evito',
        peso_e: 0.2,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 65,
        examen_id: 50,
        texto: 'Si recibes una noticia negativa, ¿qué haces?',
        peso_pregunta: 1.0,
        a: 'Me preocupo demasiado',
        peso_a: 0.2,
        b: 'Tomo medidas para mejorar',
        peso_b: 0.9,
        c: 'Busco el lado positivo',
        peso_c: 1.0,
        d: 'La dejo afectarme',
        peso_d: 0.3,
        e: 'Comparto la negatividad',
        peso_e: 0.1,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 66,
        examen_id: 50,
        texto: '¿Cómo motivas a un compañero desanimado?',
        peso_pregunta: 1.0,
        a: 'Le digo que siga adelante',
        peso_a: 0.9,
        b: 'Le doy palabras de aliento',
        peso_b: 1.0,
        c: 'Le critico',
        peso_c: 0.1,
        d: 'Le ignoro',
        peso_d: 0.2,
        e: 'Le ofrezco ayuda',
        peso_e: 0.8,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 67,
        examen_id: 50,
        texto: '¿Qué haces si un equipo no está funcionando bien?',
        peso_pregunta: 1.0,
        a: 'Me aparto del equipo',
        peso_a: 0.2,
        b: 'Critico a los demás',
        peso_b: 0.1,
        c: 'Propongo soluciones',
        peso_c: 1.0,
        d: 'Intento mejorar el ambiente',
        peso_d: 0.8,
        e: 'Espero que mejore',
        peso_e: 0.5,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 68,
        examen_id: 50,
        texto: '¿Cómo reaccionas si te rechazan una idea?',
        peso_pregunta: 1.0,
        a: 'Me siento frustrado',
        peso_a: 0.3,
        b: 'Culpo a los demás',
        peso_b: 0.1,
        c: 'Dejo de intentarlo',
        peso_c: 0.2,
        d: 'Propongo otra mejor',
        peso_d: 1.0,
        e: 'Pido retroalimentación',
        peso_e: 0.9,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 69,
        examen_id: 50,
        texto: '¿Qué haces si enfrentas un día difícil?',
        peso_pregunta: 1.0,
        a: 'Tomo un descanso y sigo adelante',
        peso_a: 1.0,
        b: 'Intento superarlo solo',
        peso_b: 0.6,
        c: 'Busco apoyo',
        peso_c: 0.7,
        d: 'Me quejo todo el día',
        peso_d: 0.2,
        e: 'Renuncio a mis tareas',
        peso_e: 0.1,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      // --- Ética (examen 51) -------------------------------------------------
      {
        id: 70,
        examen_id: 51,
        texto: '¿Qué harías si te piden hacer algo indebido?',
        peso_pregunta: 1.0,
        a: 'Intento justificarme',
        peso_a: 0.2,
        b: 'Lo ignoro',
        peso_b: 0.3,
        c: 'Lo hago por miedo',
        peso_c: 0.1,
        d: 'Me niego y reporto la situación',
        peso_d: 1.0,
        e: 'Lo hago sin pensar',
        peso_e: 0.1,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 71,
        examen_id: 51,
        texto: '¿Cómo manejas información confidencial?',
        peso_pregunta: 1.0,
        a: 'La comparto sin permiso',
        peso_a: 0.1,
        b: 'La mantengo segura',
        peso_b: 1.0,
        c: 'La ignoro',
        peso_c: 0.2,
        d: 'La olvido',
        peso_d: 0.3,
        e: 'Solo la comparto con autorización',
        peso_e: 0.9,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 72,
        examen_id: 51,
        texto: '¿Qué haces si encuentras a alguien robando?',
        peso_pregunta: 1.0,
        a: 'Me uno al robo',
        peso_a: 0.1,
        b: 'Lo reporto inmediatamente',
        peso_b: 1.0,
        c: 'Intento confrontarlo solo',
        peso_c: 0.8,
        d: 'Lo ignoro',
        peso_d: 0.2,
        e: 'Le advierto',
        peso_e: 0.5,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 73,
        examen_id: 51,
        texto: '¿Cómo actúas si cometes un error grave?',
        peso_pregunta: 1.0,
        a: 'Lo minimizo',
        peso_a: 0.3,
        b: 'Escondo el error',
        peso_b: 0.2,
        c: 'Espero que no se note',
        peso_c: 0.1,
        d: 'Culpo a otros',
        peso_d: 0.1,
        e: 'Lo admito y busco corregirlo',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 74,
        examen_id: 51,
        texto: '¿Qué haces si alguien no sigue las reglas?',
        peso_pregunta: 1.0,
        a: 'Lo reporto',
        peso_a: 1.0,
        b: 'Me uno a la infracción',
        peso_b: 0.1,
        c: 'Lo ignoro',
        peso_c: 0.2,
        d: 'Intento hablar con la persona',
        peso_d: 0.9,
        e: 'Lo dejo pasar',
        peso_e: 0.3,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 75,
        examen_id: 51,
        texto: '¿Cómo manejas tus responsabilidades laborales?',
        peso_pregunta: 1.0,
        a: 'Cumplo siempre mis tareas',
        peso_a: 1.0,
        b: 'Dependo de otros',
        peso_b: 0.3,
        c: 'Dejo tareas incompletas',
        peso_c: 0.1,
        d: 'Solo hago lo necesario',
        peso_d: 0.5,
        e: 'Aplazo las tareas importantes',
        peso_e: 0.2,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 76,
        examen_id: 51,
        texto: '¿Qué harías si alguien te ofrece un soborno?',
        peso_pregunta: 1.0,
        a: 'Lo acepto por miedo',
        peso_a: 0.1,
        b: 'Lo acepto en secreto',
        peso_b: 0.2,
        c: 'Lo rechazo y reporto',
        peso_c: 1.0,
        d: 'Lo discuto con compañeros',
        peso_d: 0.4,
        e: 'Lo ignoro',
        peso_e: 0.3,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 77,
        examen_id: 51,
        texto: '¿Cómo manejas conflictos de interés?',
        peso_pregunta: 1.0,
        a: 'Lo oculto',
        peso_a: 0.3,
        b: 'Me beneficio del conflicto',
        peso_b: 0.1,
        c: 'Siempre elijo lo correcto',
        peso_c: 1.0,
        d: 'Busco ayuda para resolverlo',
        peso_d: 0.9,
        e: 'Lo ignoro',
        peso_e: 0.2,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 78,
        examen_id: 51,
        texto: '¿Qué haces si te piden mentir?',
        peso_pregunta: 1.0,
        a: 'Busco una solución honesta',
        peso_a: 0.8,
        b: 'Me niego y digo la verdad',
        peso_b: 1.0,
        c: 'Lo ignoro',
        peso_c: 0.2,
        d: 'Depende de la situación',
        peso_d: 0.4,
        e: 'Lo hago por presión',
        peso_e: 0.1,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 79,
        examen_id: 51,
        texto: '¿Cómo trabajas bajo presión?',
        peso_pregunta: 1.0,
        a: 'Hago todo rápido sin cuidado',
        peso_a: 0.2,
        b: 'Dejo que me afecte',
        peso_b: 0.3,
        c: 'Ignoro las reglas por rapidez',
        peso_c: 0.1,
        d: 'Busco apoyo para mantenerme',
        peso_d: 0.8,
        e: 'Mantengo mi ética y esfuerzo',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      // --- Curiosidad (examen 52) -------------------------------------------
      {
        id: 80,
        examen_id: 52,
        texto: '¿Qué haces cuando no entiendes algo en tu trabajo?',
        peso_pregunta: 1.0,
        a: 'Me doy por vencido',
        peso_a: 0.1,
        b: 'Lo ignoro',
        peso_b: 0.2,
        c: 'Busco información por mi cuenta',
        peso_c: 0.9,
        d: 'Espero a que me expliquen',
        peso_d: 0.4,
        e: 'Pregunto hasta entender',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 81,
        examen_id: 52,
        texto: '¿Cómo manejas una tarea nueva?',
        peso_pregunta: 1.0,
        a: 'Investigo cómo hacerla',
        peso_a: 1.0,
        b: 'Hago lo mínimo',
        peso_b: 0.3,
        c: 'Espero instrucciones',
        peso_c: 0.5,
        d: 'Dejo que alguien más la haga',
        peso_d: 0.2,
        e: 'Pido ayuda inmediatamente',
        peso_e: 0.7,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 82,
        examen_id: 52,
        texto: '¿Qué haces si surge un problema inesperado?',
        peso_pregunta: 1.0,
        a: 'Lo ignoro',
        peso_a: 0.2,
        b: 'Espero que se resuelva solo',
        peso_b: 0.1,
        c: 'Pruebo distintas soluciones',
        peso_c: 0.9,
        d: 'Analizo las causas y soluciones',
        peso_d: 1.0,
        e: 'Pido ayuda sin intentarlo',
        peso_e: 0.4,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 83,
        examen_id: 52,
        texto: '¿Cómo mejoras tus habilidades laborales?',
        peso_pregunta: 1.0,
        a: 'No le doy importancia',
        peso_a: 0.1,
        b: 'Aprendo de los errores',
        peso_b: 0.9,
        c: 'Dependo de capacitaciones externas',
        peso_c: 0.7,
        d: 'Busco constantemente aprender',
        peso_d: 1.0,
        e: 'Solo cuando me lo piden',
        peso_e: 0.3,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 84,
        examen_id: 52,
        texto: '¿Cómo reaccionas ante un tema desconocido?',
        peso_pregunta: 1.0,
        a: 'Lo evito',
        peso_a: 0.1,
        b: 'Lo dejo pasar',
        peso_b: 0.2,
        c: 'Espero a que alguien lo explique',
        peso_c: 0.3,
        d: 'Me interesa aprender más',
        peso_d: 0.9,
        e: 'Investigo para entenderlo',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 85,
        examen_id: 52,
        texto: '¿Qué haces si alguien menciona una idea nueva?',
        peso_pregunta: 1.0,
        a: 'La ignoro',
        peso_a: 0.2,
        b: 'Pregunto más sobre la idea',
        peso_b: 1.0,
        c: 'La descarto sin pensar',
        peso_c: 0.1,
        d: 'Le critico sin analizar',
        peso_d: 0.3,
        e: 'La investigo por mi cuenta',
        peso_e: 0.9,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 86,
        examen_id: 52,
        texto: '¿Cómo abordas un proyecto complejo?',
        peso_pregunta: 1.0,
        a: 'Espero instrucciones',
        peso_a: 0.3,
        b: 'Me frustro al inicio',
        peso_b: 0.2,
        c: 'Busco información para comprender',
        peso_c: 0.9,
        d: 'Divido en partes y estudio cada una',
        peso_d: 1.0,
        e: 'Dejo que alguien lo resuelva',
        peso_e: 0.1,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 87,
        examen_id: 52,
        texto: '¿Qué haces si un compañero sabe más que tú?',
        peso_pregunta: 1.0,
        a: 'Evito colaborar',
        peso_a: 0.2,
        b: 'Intento igualar sus habilidades',
        peso_b: 0.9,
        c: 'Le pido aprender de él',
        peso_c: 1.0,
        d: 'Lo ignoro',
        peso_d: 0.1,
        e: 'Compito sin preguntar',
        peso_e: 0.3,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 88,
        examen_id: 52,
        texto: '¿Cómo reaccionas ante una capacitación?',
        peso_pregunta: 1.0,
        a: 'Solo asisto por obligación',
        peso_a: 0.3,
        b: 'Me distraigo',
        peso_b: 0.1,
        c: 'Tomo notas para aprender',
        peso_c: 0.9,
        d: 'Participo activamente',
        peso_d: 1.0,
        e: 'No le doy importancia',
        peso_e: 0.2,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 89,
        examen_id: 52,
        texto: '¿Qué haces si recibes una crítica constructiva?',
        peso_pregunta: 1.0,
        a: 'La ignoro',
        peso_a: 0.2,
        b: 'Me siento mal',
        peso_b: 0.3,
        c: 'Pido más detalles para aprender',
        peso_c: 0.9,
        d: 'La rechazo',
        peso_d: 0.1,
        e: 'La uso para mejorar',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      // --- Integridad (examen 53) -------------------------------------------
      {
        id: 90,
        examen_id: 53,
        texto: '¿Qué harías si encuentras un error que afecta a alguien?',
        peso_pregunta: 1.0,
        a: 'Espero a que lo noten',
        peso_a: 0.4,
        b: 'Lo corrijo sin decir nada',
        peso_b: 0.8,
        c: 'Lo ignoro',
        peso_c: 0.2,
        d: 'Lo reporto y corrijo',
        peso_d: 1.0,
        e: 'Culpo a alguien más',
        peso_e: 0.1,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 91,
        examen_id: 53,
        texto: '¿Cómo manejas información sensible?',
        peso_pregunta: 1.0,
        a: 'La ignoro',
        peso_a: 0.2,
        b: 'La protejo y uso correctamente',
        peso_b: 1.0,
        c: 'La pierdo fácilmente',
        peso_c: 0.1,
        d: 'La comparto sin permiso',
        peso_d: 0.1,
        e: 'La comparto con amigos',
        peso_e: 0.3,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 92,
        examen_id: 53,
        texto: '¿Qué haces si alguien te pide mentir?',
        peso_pregunta: 1.0,
        a: 'Lo discuto primero',
        peso_a: 0.7,
        b: 'Lo evito sin enfrentar',
        peso_b: 0.3,
        c: 'Lo hago por presión',
        peso_c: 0.1,
        d: 'Acepto si es necesario',
        peso_d: 0.2,
        e: 'Me niego y explico por qué',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 93,
        examen_id: 53,
        texto: '¿Cómo manejas un conflicto ético?',
        peso_pregunta: 1.0,
        a: 'Busco ayuda para resolverlo',
        peso_a: 0.9,
        b: 'Lo ignoro',
        peso_b: 0.2,
        c: 'Lo oculto',
        peso_c: 0.1,
        d: 'Elijo siempre lo correcto',
        peso_d: 1.0,
        e: 'Espero que otros decidan',
        peso_e: 0.3,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 94,
        examen_id: 53,
        texto: '¿Qué haces si un compañero actúa mal?',
        peso_pregunta: 1.0,
        a: 'Me uno a su acción',
        peso_a: 0.1,
        b: 'Lo apoyo sin pensar',
        peso_b: 0.1,
        c: 'Lo confronto y ayudo a corregir',
        peso_c: 1.0,
        d: 'Lo ignoro',
        peso_d: 0.2,
        e: 'Lo reporto',
        peso_e: 0.9,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 95,
        examen_id: 53,
        texto: '¿Cómo reaccionas si cometes un error?',
        peso_pregunta: 1.0,
        a: 'Intento corregirlo solo',
        peso_a: 0.9,
        b: 'Lo minimizo',
        peso_b: 0.3,
        c: 'Lo escondo',
        peso_c: 0.2,
        d: 'Lo admito y busco corregirlo',
        peso_d: 1.0,
        e: 'Culpo a otros',
        peso_e: 0.1,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 96,
        examen_id: 53,
        texto: '¿Qué haces si encuentras dinero perdido?',
        peso_pregunta: 1.0,
        a: 'Lo dejo en su lugar',
        peso_a: 0.3,
        b: 'Busco al dueño o reporto',
        peso_b: 1.0,
        c: 'Lo ignoro',
        peso_c: 0.2,
        d: 'Me lo guardo',
        peso_d: 0.1,
        e: 'Lo comparto con amigos',
        peso_e: 0.2,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 97,
        examen_id: 53,
        texto: '¿Cómo manejas tus tareas diarias?',
        peso_pregunta: 1.0,
        a: 'Cumplo todas mis responsabilidades',
        peso_a: 1.0,
        b: 'Aplazo tareas importantes',
        peso_b: 0.2,
        c: 'Dejo todo incompleto',
        peso_c: 0.1,
        d: 'Solo hago lo necesario',
        peso_d: 0.3,
        e: 'Dependo de otros',
        peso_e: 0.4,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 98,
        examen_id: 53,
        texto: '¿Qué harías si alguien te ofrece un soborno?',
        peso_pregunta: 1.0,
        a: 'Lo acepto en secreto',
        peso_a: 0.1,
        b: 'Lo considero',
        peso_b: 0.2,
        c: 'Lo ignoro',
        peso_c: 0.3,
        d: 'Lo rechazo y reporto',
        peso_d: 1.0,
        e: 'Lo discuto con amigos',
        peso_e: 0.4,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 99,
        examen_id: 53,
        texto: '¿Cómo manejas decisiones difíciles?',
        peso_pregunta: 1.0,
        a: 'Dependo de otros para decidir',
        peso_a: 0.3,
        b: 'Analizo todas las opciones',
        peso_b: 0.9,
        c: 'Escojo la más fácil',
        peso_c: 0.1,
        d: 'Ignoro las consecuencias',
        peso_d: 0.2,
        e: 'Elijo siempre la opción correcta',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      // --- Empatía (examen 55) ----------------------------------------------
      {
        id: 110,
        examen_id: 55,
        texto: '¿Qué haces si un compañero está visiblemente molesto?',
        peso_pregunta: 1.0,
        a: 'Le digo que supere el problema',
        peso_a: 0.2,
        b: 'Le pregunto si quiere hablar al respecto',
        peso_b: 1.0,
        c: 'Cambio de tema para distraerlo',
        peso_c: 0.4,
        d: 'Lo ignoro',
        peso_d: 0.1,
        e: 'Lo dejo solo para que se calme',
        peso_e: 0.6,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 111,
        examen_id: 55,
        texto: '¿Cómo reaccionas cuando alguien comparte un problema personal?',
        peso_pregunta: 1.0,
        a: 'Escucho atentamente y ofrezco apoyo',
        peso_a: 1.0,
        b: 'Le digo que no es tan grave',
        peso_b: 0.2,
        c: 'Cambio de tema para evitar incomodidad',
        peso_c: 0.3,
        d: 'Doy consejos rápidos sin escuchar mucho',
        peso_d: 0.5,
        e: 'Lo evito porque no sé qué decir',
        peso_e: 0.1,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 112,
        examen_id: 55,
        texto: 'Si ves a alguien llorando en el trabajo, ¿qué haces?',
        peso_pregunta: 1.0,
        a: 'Finjo no haberlo visto',
        peso_a: 0.1,
        b: 'Le pido que deje de llorar',
        peso_b: 0.1,
        c: 'Busco a alguien más para ayudarlo',
        peso_c: 0.7,
        d: 'Me acerco y le ofrezco ayuda o consuelo',
        peso_d: 1.0,
        e: 'Lo ignoro para no incomodarlo',
        peso_e: 0.2,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 113,
        examen_id: 55,
        texto: '¿Cómo reaccionas si alguien se equivoca por estar distraído?',
        peso_pregunta: 1.0,
        a: 'Solo corrijo su error sin más comentarios',
        peso_a: 0.8,
        b: 'Le ignoro y dejo que lo resuelva',
        peso_b: 0.3,
        c: 'Le pregunto si está bien y si necesita ayuda',
        peso_c: 1.0,
        d: 'Me quejo con otros compañeros',
        peso_d: 0.2,
        e: 'Le digo que debe concentrarse más',
        peso_e: 0.5,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 114,
        examen_id: 55,
        texto: '¿Qué haces si notas que un cliente está frustrado?',
        peso_pregunta: 1.0,
        a: 'Evito interactuar con él',
        peso_a: 0.1,
        b: 'Le digo que tenga paciencia',
        peso_b: 0.3,
        c: 'Le ofrezco una solución rápida sin empatizar',
        peso_c: 0.7,
        d: 'Me disculpo sin ofrecer ayuda',
        peso_d: 0.4,
        e: 'Intento entender su frustración y solucionarlo',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 115,
        examen_id: 55,
        texto: '¿Cómo manejas una conversación con alguien enojado?',
        peso_pregunta: 1.0,
        a: 'Me defiendo inmediatamente',
        peso_a: 0.2,
        b: 'Lo interrumpo para explicar mi punto',
        peso_b: 0.3,
        c: 'Le digo que no tiene razón',
        peso_c: 0.1,
        d: 'Escucho sin interrumpir y trato de calmarlo',
        peso_d: 1.0,
        e: 'Le pido que se calme antes de hablar',
        peso_e: 0.5,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 116,
        examen_id: 55,
        texto: 'Si un compañero está enfrentando problemas personales, ¿cómo reaccionas?',
        peso_pregunta: 1.0,
        a: 'Evito involucrarme',
        peso_a: 0.2,
        b: 'Le ofrezco consejos genéricos',
        peso_b: 0.5,
        c: 'Le ignoro porque no es asunto mío',
        peso_c: 0.1,
        d: 'Le digo que debe separarlo del trabajo',
        peso_d: 0.6,
        e: 'Le ofrezco mi apoyo y disponibilidad',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 117,
        examen_id: 55,
        texto: '¿Cómo actúas si un cliente se queja con razón?',
        peso_pregunta: 1.0,
        a: 'Le escucho y le aseguro que se resolverá',
        peso_a: 1.0,
        b: 'Le digo que no es mi culpa',
        peso_b: 0.2,
        c: 'Le doy la razón sin resolver el problema',
        peso_c: 0.4,
        d: 'Le ignoro hasta que se calme',
        peso_d: 0.1,
        e: 'Le ofrezco un descuento rápido para calmarlo',
        peso_e: 0.8,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 118,
        examen_id: 55,
        texto: '¿Qué haces si alguien parece ansioso o preocupado?',
        peso_pregunta: 1.0,
        a: 'Le doy una respuesta rápida para terminar la conversación',
        peso_a: 0.2,
        b: 'Le digo que no se preocupe tanto',
        peso_b: 0.7,
        c: 'Le ignoro porque no quiero involucrarme',
        peso_c: 0.1,
        d: 'Le pregunto si necesita algo y escucho',
        peso_d: 1.0,
        e: 'Le sugiero hablar con alguien más',
        peso_e: 0.6,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 119,
        examen_id: 55,
        texto: 'Si te critican de manera constructiva, ¿cómo respondes?',
        peso_pregunta: 1.0,
        a: 'Me defiendo rápidamente',
        peso_a: 0.3,
        b: 'Me enojo y lo tomo personal',
        peso_b: 0.1,
        c: 'Agradezco la crítica y reflexiono sobre ella',
        peso_c: 1.0,
        d: 'Cambio de tema para evitarlo',
        peso_d: 0.2,
        e: 'Digo que lo entenderé después',
        peso_e: 0.6,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      // --- Autoconciencia (examen 54) ---------------------------------------
      {
        id: 120,
        examen_id: 54,
        texto: '¿Qué haces si cometes un error en el trabajo?',
        peso_pregunta: 1.0,
        a: 'Lo reconozco y busco solucionarlo',
        peso_a: 1.0,
        b: 'Espero a que nadie lo note',
        peso_b: 0.2,
        c: 'Culpo a otros',
        peso_c: 0.1,
        d: 'Lo oculto y sigo adelante',
        peso_d: 0.1,
        e: 'Minimizo el impacto del error',
        peso_e: 0.4,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 121,
        examen_id: 54,
        texto: '¿Cómo reaccionas si recibes una crítica constructiva?',
        peso_pregunta: 1.0,
        a: 'Digo que estoy de acuerdo pero no cambio nada',
        peso_a: 0.4,
        b: 'Evito escuchar la crítica',
        peso_b: 0.1,
        c: 'La ignoro porque no es importante',
        peso_c: 0.2,
        d: 'Me molesto y la rechazo',
        peso_d: 0.1,
        e: 'Agradezco y reflexiono sobre la crítica',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 122,
        examen_id: 54,
        texto: '¿Qué haces si sientes que estás perdiendo el control emocional?',
        peso_pregunta: 1.0,
        a: 'Me tomo un momento para calmarme y analizar',
        peso_a: 1.0,
        b: 'Lo ignoro y sigo adelante',
        peso_b: 0.3,
        c: 'Reacciono sin pensar',
        peso_c: 0.1,
        d: 'Busco una distracción para olvidarlo',
        peso_d: 0.5,
        e: 'Le grito a alguien para liberar la emoción',
        peso_e: 0.1,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 123,
        examen_id: 54,
        texto: '¿Cómo manejas tus debilidades en el trabajo?',
        peso_pregunta: 1.0,
        a: 'Trato de ocultarlas',
        peso_a: 0.2,
        b: 'Reconozco mis áreas de mejora y busco desarrollarlas',
        peso_b: 1.0,
        c: 'Dependo de otros para cubrirlas',
        peso_c: 0.3,
        d: 'Las ignoro porque no son importantes',
        peso_d: 0.1,
        e: 'Evito responsabilidades donde pueden notarse',
        peso_e: 0.4,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 124,
        examen_id: 54,
        texto: 'Si tienes éxito en una tarea, ¿cómo te sientes?',
        peso_pregunta: 1.0,
        a: 'Me siento mejor que mis compañeros',
        peso_a: 0.1,
        b: 'Creo que fue suerte y no lo repito',
        peso_b: 0.4,
        c: 'Lo presumo para obtener reconocimiento',
        peso_c: 0.3,
        d: 'Lo ignoro porque es lo normal',
        peso_d: 0.2,
        e: 'Contento y motivado para seguir mejorando',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 125,
        examen_id: 54,
        texto: '¿Qué haces si no sabes cómo abordar una tarea?',
        peso_pregunta: 1.0,
        a: 'Reconozco que necesito ayuda y la pido',
        peso_a: 1.0,
        b: 'Espero a que alguien más lo resuelva',
        peso_b: 0.3,
        c: 'Busco una excusa para no hacerlo',
        peso_c: 0.2,
        d: 'Me frustro y dejo de intentarlo',
        peso_d: 0.1,
        e: 'Intento hacerlo sin pedir ayuda aunque salga mal',
        peso_e: 0.5,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 126,
        examen_id: 54,
        texto: '¿Cómo reaccionas cuando un proyecto no sale como esperabas?',
        peso_pregunta: 1.0,
        a: 'Lo olvido para no preocuparme',
        peso_a: 0.3,
        b: 'Culpo a los demás por los errores',
        peso_b: 0.2,
        c: 'Analizo qué salió mal y cómo mejorar',
        peso_c: 1.0,
        d: 'Me culpo completamente por el fracaso',
        peso_d: 0.4,
        e: 'Me enojo y lo abandono',
        peso_e: 0.1,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 127,
        examen_id: 54,
        texto: '¿Qué haces para manejar el estrés en el trabajo?',
        peso_pregunta: 1.0,
        a: 'Espero a que alguien me ayude',
        peso_a: 0.2,
        b: 'Identifico la causa y busco soluciones',
        peso_b: 1.0,
        c: 'Me desquito con los demás',
        peso_c: 0.1,
        d: 'Evito las responsabilidades que me estresan',
        peso_d: 0.3,
        e: 'Trato de ignorarlo hasta que pase',
        peso_e: 0.4,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 128,
        examen_id: 54,
        texto: '¿Cómo evalúas tu desempeño en una tarea difícil?',
        peso_pregunta: 1.0,
        a: 'Reflexiono sobre lo que hice bien y mal',
        peso_a: 1.0,
        b: 'Me doy mucho crédito aunque haya errores',
        peso_b: 0.4,
        c: 'Evito pensar en lo que pasó',
        peso_c: 0.2,
        d: 'Solo pienso en los errores',
        peso_d: 0.5,
        e: 'Espero a que otros evalúen por mí',
        peso_e: 0.3,
        respuesta_correcta: 'a',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 129,
        examen_id: 54,
        texto: '¿Qué haces si un compañero te supera en desempeño?',
        peso_pregunta: 1.0,
        a: 'Me desmotivo porque no soy tan bueno',
        peso_a: 0.2,
        b: 'Lo ignoro porque no es relevante',
        peso_b: 0.3,
        c: 'Reconozco su esfuerzo y me motivo a mejorar',
        peso_c: 1.0,
        d: 'Intento minimizar su éxito frente a otros',
        peso_d: 0.1,
        e: 'Trato de competir con él a toda costa',
        peso_e: 0.4,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 130,
        examen_id: 2,
        texto: '¿Cuál es el primer paso al atender a un cliente?',
        peso_pregunta: 1.0,
        a: 'Preguntar qué desea ordenar',
        peso_a: 0.8,
        b: 'Esperar a que el cliente hable',
        peso_b: 0.5,
        c: 'Ignorarlo hasta que pida atención',
        peso_c: 0.1,
        d: 'Saludar con una sonrisa y presentarse',
        peso_d: 1.0,
        e: 'Llevarle el menú sin decir nada',
        peso_e: 0.2,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 131,
        examen_id: 2,
        texto: '¿Qué significa "mise en place"?',
        peso_pregunta: 1.0,
        a: 'Montar la mesa',
        peso_a: 0.8,
        b: 'Preparación previa',
        peso_b: 1.0,
        c: 'Servir los platos',
        peso_c: 0.5,
        d: 'Cocinar los alimentos',
        peso_d: 0.3,
        e: 'Organizar la cocina',
        peso_e: 0.4,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 132,
        examen_id: 2,
        texto: '¿Cómo se recomienda sugerir un platillo al cliente?',
        peso_pregunta: 1.0,
        a: 'Diciendo que es lo único disponible',
        peso_a: 0.3,
        b: 'Describiendo los ingredientes y su sabor',
        peso_b: 1.0,
        c: 'Ofreciendo el platillo más caro',
        peso_c: 0.2,
        d: 'Ofreciendo lo que más se vende',
        peso_d: 0.8,
        e: 'Insistiendo hasta que acepte',
        peso_e: 0.1,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 133,
        examen_id: 2,
        texto: '¿Qué debes hacer si un cliente tiene una queja?',
        peso_pregunta: 1.0,
        a: 'Culpar a la cocina',
        peso_a: 0.2,
        b: 'Llamar al gerente sin investigar',
        peso_b: 0.5,
        c: 'Ignorarlo porque siempre se quejan',
        peso_c: 0.1,
        d: 'Decirle que no es tu responsabilidad',
        peso_d: 0.3,
        e: 'Escuchar con atención y ofrecer una solución',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 134,
        examen_id: 2,
        texto: '¿Qué incluye un buen servicio al cliente?',
        peso_pregunta: 1.0,
        a: 'Ser simpático aunque el pedido esté mal',
        peso_a: 0.5,
        b: 'Llevar lo que piden sin preguntar más',
        peso_b: 0.4,
        c: 'Solo rapidez para entregar los pedidos',
        peso_c: 0.3,
        d: 'Rapidez, cortesía y atención a los detalles',
        peso_d: 1.0,
        e: 'Hablar con ellos para entretenerlos',
        peso_e: 0.2,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 135,
        examen_id: 2,
        texto: '¿Qué hacer si un cliente pregunta por ingredientes de un platillo?',
        peso_pregunta: 1.0,
        a: 'Decir que no sabes y continuar con el servicio',
        peso_a: 0.2,
        b: 'Inventar una respuesta rápida',
        peso_b: 0.1,
        c: 'Decir que todo es delicioso sin detalles',
        peso_c: 0.3,
        d: 'Ignorar la pregunta',
        peso_d: 0.1,
        e: 'Responder con seguridad o consultar al chef',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 136,
        examen_id: 2,
        texto: '¿Cuál es el procedimiento correcto para servir bebidas?',
        peso_pregunta: 1.0,
        a: 'Servir solo si el cliente lo pide dos veces',
        peso_a: 0.2,
        b: 'Llevar varias copas juntas aunque no sea seguro',
        peso_b: 0.4,
        c: 'Servir rápido sin importar la presentación',
        peso_c: 0.3,
        d: 'Tomar la copa por el borde para mayor estabilidad',
        peso_d: 0.1,
        e: 'Tomar la copa por la base y presentarla adecuadamente',
        peso_e: 1.0,
        respuesta_correcta: 'e',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 137,
        examen_id: 2,
        texto: '¿Qué hacer si un cliente es alérgico a un ingrediente?',
        peso_pregunta: 1.0,
        a: 'Evitar atenderlo porque es complicado',
        peso_a: 0.1,
        b: 'Confirmar con la cocina que el platillo es seguro',
        peso_b: 1.0,
        c: 'Pedirle que él decida sin ayuda',
        peso_c: 0.3,
        d: 'Decirle que no hay problema sin verificar',
        peso_d: 0.2,
        e: 'Ofrecerle algo sin mencionar los ingredientes',
        peso_e: 0.4,
        respuesta_correcta: 'b',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 138,
        examen_id: 2,
        texto: '¿Qué debe hacer un mesero al finalizar el servicio?',
        peso_pregunta: 1.0,
        a: 'Esperar la propina sin despedirse',
        peso_a: 0.1,
        b: 'Entregar la cuenta y marcharse rápido',
        peso_b: 0.5,
        c: 'Despedirse sin verificar su satisfacción',
        peso_c: 0.3,
        d: 'Agradecer al cliente y preguntar si necesita algo más',
        peso_d: 1.0,
        e: 'Ignorar al cliente una vez que pague',
        peso_e: 0.2,
        respuesta_correcta: 'd',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
      {
        id: 139,
        examen_id: 2,
        texto: '¿Cómo manejar una mesa ocupada cuando llegan más clientes?',
        peso_pregunta: 1.0,
        a: 'Apresurar a los que ya están sentados',
        peso_a: 0.3,
        b: 'Atender solo a los nuevos clientes primero',
        peso_b: 0.5,
        c: 'Atender a todos organizadamente sin descuidar a nadie',
        peso_c: 1.0,
        d: 'Dejar que esperen sin explicación',
        peso_d: 0.2,
        e: 'Ignorar a los nuevos para enfocarte en los actuales',
        peso_e: 0.1,
        respuesta_correcta: 'c',
        createdAt: DateTime.fromSQL('2025-02-18 03:59:32'),
        updatedAt: DateTime.fromSQL('2025-02-18 03:59:32'),
      },
    ])
  }
}
