[phases.setup]
node_version = "20.11.1"

# 👇  NUEVO: instalamos todo y permitimos scripts
[phases.install]
cmds = ["npm ci --ignore-scripts=false --omit=dev=false"]

# (opcional) deja claro el build, pero no es imprescindible
[phases.build]
cmds = ["npm run build"]
